### ISSUE TITLE
Is it possible to return text from a function?

### ISSUE THREAD

**Issue by naro** [MightyPork/sdscp#2]
Let's have the following code:
```
get_text() {
    return "Hello world";
}

main() {
    echo(get_text());
}
```

It can be compiled by SDSCP but SDS-C compiler fails on line generated  as `__rval = 'Hello world';`. Is there any nice workaround?

What I'm doing now is something like this:
```
get_text(index, param) {
    sprintf(text[index], "Hello ", param);
}

main() {
    get_text(0, "world");  // fill-in text[0]
    echo(text[0]);  // display text[0]
}
```
but I don't like it. My use case is - I would like to pass function result to the echo or http_get. I understand it is a SDS-C limitation.

Thanks

**Comment by MightyPork** [comment]
I don't think the SDS-C compiler can handle passing strings at all, it's string support (IIRC) is limited to literals in built-in function calls, and some strange stuff with the `text[]` array.

Not sure if implementing "string variables" in SDSCP is worth the effort.

**Comment by naro** [comment]
Could SDSCP emit a warning or error message if function returns a text ?

**Comment by MightyPork** [comment]
good idea

**Comment by MightyPork** [comment]
Should be fixed in the dev branch, can you please try if your programs compile ok with it?

I've also added some extra optimization to the code mutator, so it should now remove things like:

```
goto foo;
label foo:

// or
if (1) goto foo;
label foo:
```

if label `foo` is not used anywhere else

**Comment by naro** [comment]
Thanks,
my program compiles fine.
If I add return "Hello" somewhere I get an error:

```SDS-C does not support string variables, at __rval = 'Hello';```

so everything seems to be fine. Thank you

**Comment by MightyPork** [comment]
hm.. that can be better yet.

I moved the check into mutator, so now the message is:

```
Can't return a string literal, at: "abc"
```

Should be easier to debug. Will make a new release in a few minutes.
