### ISSUE TITLE
Invalid syntax of _abs in utils.c

### ISSUE THREAD

**Issue by naro** [MightyPork/sdscp#3]
https://github.com/MightyPork/sdscp/blob/243c2858929c2e82610a59683249cc39648b4f7f/example/library/utils.c#L7

Wrong:
`#define _abs(x) ((x) * (1 - (2 * ((x) < 0)))`
Correct:
`#define _abs(x) ((x) * (1 - (2 * ((x) < 0))))`

**Comment by MightyPork** [comment]
good catch, please send a pull request & I'll merge it.
